Improved helpers

diff --git a/.db_helpers/reset-db b/.db_helpers/reset-db
--- a/.db_helpers/reset-db
+++ b/.db_helpers/reset-db
@@ -1,5 +1,15 @@
 #!/usr/bin/env zsh
 
+# Add the necessary users to the database.
+function create-db-users() {
+    echo "${DB_PASSWORD} ${DB_PASSWORD}" | createuser -d -l ${DB_USERNAME}
+    if [ $? -eq 0 ]; then
+        echo "Added user ${DB_USERNAME} with password ${DB_PASSWORD}."
+    else
+        echo "Could not create the user ${DB_USERNAME}."
+    fi
+}
+
 # Creates databases required by Pumbaa.
 function create-dbs() {
     createdb ${DB_NAME}
